### ISSUE TITLE
west team mirror

### ISSUE THREAD

**Issue by mrcamp** [suitcase24/SoccerSimulator#1]
The west team's ballDirection seems to be correctly mirrored, but their localArea is not mirrored. 

For example: assume a western player is in the space directly to the east/right of the ball. 
The actual direction to the ball is west (3) but it will correctly mirror to say that ballDirection is east (5).

For the localArea array though, localArea[E] will have 0 (EMPTY) and localArea[W] will have 2 (BALL).

**Comment by suitcase24** [comment]
I am pretty sure I have fixed the issue.  Local area and ballDirection are the same but the players x and the ball's x have been reflected across the field.  It should now always appear to the player algorithms that the player is on the east team.
